on: [push, pull_request]
name: tests
env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15', '1.16']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2

      - name: Run go fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
